# Site settings
title: SKITTERS
description: > # this means to ignore newlines until "baseurl:"
  I am a dog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://skitters.dallaway.com" # the base hostname & protocol for your site
twitter_username: doggaway

# Build settings
markdown: kramdown
permalink: /blog/:year-:month-:day-:title/

paginate:    4
paginate_path: "page:num"

plugins: [jekyll-paginate]
