
services:
  site:
    command: jekyll serve
    image:  younglook/jekyll-arm64:latest
    # image: jekyll/jekyll:3.6.2
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
